### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Rederpz** [candyfodder/Caroline#1]
Yeah hi... been trying to get this to work for the last 30 minutes, I start Minecraft and run the application but it doesn't affect my game at all. Not sure what I'm doing wrong... If you have any ideas on why it's not working let me know, because for now this appears to be an issue on your end and not mine.

**Comment by RealXor** [comment]
yes same issue here still nothing happening I've used different ram sticks but nothing changed, please fix

**Comment by candyfodder** [comment]
Fixed for windows machines. Thanks Kosel in TCG Discord.
